version: '3.9'

services:
  mirakurun:
    image: chinachu/mirakurun:${MIRAKURUN_IMAGE_TAG:-latest}
    container_name: mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    ports:
      - "40772:40772"
      - "9229:9229"
    volumes:
      - type: bind
        source: ./mirakurun/opt
        target: /opt
      - type: bind
        source: ./mirakurun/conf
        target: /app-config
      - type: bind
        source: ./mirakurun/data
        target: /app-data
    environment:
      TZ: "Asia/Tokyo"
      BCAS_KEYS_FILE: /src/libyakisoba/src/bcas_keys
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
    devices:
      - /dev/px4video0
      - /dev/px4video1
      - /dev/px4video2
      - /dev/px4video3
      - /dev/px4video4
      - /dev/px4video5
      - /dev/px4video6
      - /dev/px4video7
